/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
/* Header for class com_tongfang_opticalmagnetic_SerialPort */

#ifndef _Included_com_industry_printer_Serial_SerialPort
#define _Included_com_industry_printer_Serial_SerialPort
#ifdef __cplusplus
extern "C" {
#endif

#ifndef LOG_TAG
#define LOG_TAG "SerialPort(Native)"
#endif
#define LOGV(...) __android_log_print(ANDROID_LOG_VERBOSE, LOG_TAG, __VA_ARGS__)
#define LOGD(...) __android_log_print(ANDROID_LOG_DEBUG, LOG_TAG, __VA_ARGS__)
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)
#define LOGW(...) __android_log_print(ANDROID_LOG_WARN, LOG_TAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)
#define LOGF(...) __android_log_print(ANDROID_LOG_FATAL, LOG_TAG, __VA_ARGS__)

/*
 * Class:     com_industry_printer_Serial_SerialPort
 * Method:    OpenSerialPort
 * Signature: (Ljava/lang/String;I)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL com_industry_printer_Serial_SerialPort_OpenSerialPort
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_industry_printer_Serial_SerialPort
 * Method:    CloseSerialPort
 * Signature: ()I
 */
JNIEXPORT jint JNICALL com_industry_printer_Serial_SerialPort_CloseSerialPort
  (JNIEnv *, jobject);

/*
 * Class:     com_industry_printer_Serial_SerialPort
 * Method:    ReadSerialPort
 * Signature: ()I
 */

JNIEXPORT jint JNICALL com_industry_printer_Serial_SerialPort_ReadSerialPort
  (JNIEnv *, jobject);

/*
 * Class:     com_industry_printer_Serial_SerialPort
 * Method:    WriteSerialPort
 * Signature: ([C)I
 */
/*
JNIEXPORT jint JNICALL com_industry_printer_Serial_SerialPort_WriteSerialPort
  (JNIEnv *, jobject, jcharArray);
*/

/*
* Class:     com_industry_printer_Serial_SerialPort
* Method:    GetSectorCount
* Signature: ()I
*/
JNIEXPORT jint JNICALL com_industry_printer_Serial_SerialPort_GetSectorCount
(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
